### ISSUE TITLE
Different decimal and group separator used error

### ISSUE THREAD

**Issue by AlesMrak** [BobKnothe/autoNumeric#123]
Hi, in the code 

/** allows locale decimal seperator to be a comma */
                if (testValue === $this.attr('value')) {
                    value = value.replace(',', '.');
                }

shouldn't be the right solution to replace proper configured decimal sepator like this (it could be point separator and not comma):

if (testValue === $this.attr('value')) {
                    value = value.replace(settings.aSep, '' );
                    value = value.replace(settings.aDec, '.' );
                }

Best regards
Ales

**Comment by BobKnothe** [comment]
Ales,

I see you point but!

This has been a rather sticky wicket, when I opened the door from 'nnnn.nn' to 'nnnn,nn' my headaches multiplied.

I tried to draw the line and not allow thousand separator. If I allow thousand separator why not the currency sign and so on.

The fact is JavaScript only recognizes 'nnnn.nn' as a number and it is easy for a developer to convert.

If you can give me a compelling reason to think otherwise I will listen

Best regards,

Bob

**Comment by matejsp** [comment]
Bob hello, 

the reason to fix this is not in the set method (because set has a documentation that it accepts only "correct" numbers. The real problem and the most compelling reason to fix this is that the set method is called on init and if you want to have thousand separator that is however supported for formatting this can be a huge problem (because it corrupts user input). Try init, destroy, init on some input.

The fact is Javascript recognizes more than just nnnn.nn ...
Try: 1000,12 === autonumeric (after replace 1000.00) = OK
Try: 1.000,12 === autonumeric (after replace 1.000.00) == OK (because javascript also accept this as number and takes only last dot)
Try  1.000 === autonumeric == (after replace 1.000) FAIL because it becomes to 1 (instead of set value is not numberic)

IMHO: 
- consistency between get and set and init and even using different values is very important.
- most importantly corrupting the user input should never EVER be allowed behaviour

perhaps this fix would be even better by using the existing methods (fixes even the currency):
```javascript
        /** allows locale decimal separator to be a comma */
        if ((testValue === $this.attr('value') || testValue === $this.text()) && settings.runOnce === false) {
            value = value=autoStrip(value, settings);
            value = truncateDecimal(value, settings);
            value = fixNumber(s, settings.aDec, settings.aNeg);
                }
```

Or alternative would be to call just on init:
$this.autoNumeric('set', $this.autoNumeric('get'));
instead of problematic:
$this.autoNumeric('set', $this.val()); or $this.autoNumeric('set', $this.text());

Best regards,
Matej

**Comment by BobKnothe** [comment]
Matej,

Thanks for your input and I see your point. Just to clarify under 1.9.34 with defaults the following occurs: 

1000.12 === autonumeric (result 1,000.00) = OK
1000,12 === autonumeric (result 1,000.00)  = OK
1.000.12 === autonumeric (result 1.000.00) = fails & error is thrown
1.000,12 === autonumeric (result 1.000.00) = fails & error is thrown

This little routine was to allow the developer to use their locale decimal point in the in the html code but not when 'set' setting a value after the page has loaded.

The aForm option is to allow the developer to choose whether or not they want to auto format on page load example aForm: false and the input value = "$1,000.12" does not throw an error.

Maybe a new option locDec: false / true in version 2 might allow this:  

if ((testValue === $this.attr('value') || testValue === $this.text()) && settings.runOnce === false) {      
 to 
if (locDec) {

If I missed your point let me know?

Best regards,

Bob
