### ISSUE TITLE
type=number

### ISSUE THREAD

**Issue by mstudio** [BobKnothe/autoNumeric#125]
I noticed that inputs with type=number throw an error in the console as an unsupported type. I'm wondering if there is a reason this lib doesn't support type=number?

The reason I ask is because on iOS devices, type=number brings up a numeric keypad with the ability to enter decimals. Great plugin, thanks.

**Comment by BobKnothe** [comment]
Alex,

Setting a non-numeric "$1,234.00" value with jQuery does not work. This 
is a browser issue. The weird thing is you can type anything in the 
field but as soon as you send a value via JavaScript is do not work.

Two ways to bring the numeric keypad up:

 1. <input type="text" pattern="\d*">  use the pattern attribute -
    currently works on iOS only
 2. <input type="tel" pattern="\d*">  set the  type to telephone -
    should work on most mobile browsers - on android devices you may get
    the pause and wait buttons.

That's is the best work around until the browsers either change how the 
number type is handled or the pattern attribute is supported by all.


Hope this helps.

Bob

**Comment by mstudio** [comment]
Thanks, Bob! Sending a few beers your way, as you've saved us countless hours of dev time :)

**Comment by BobKnothe** [comment]
Alex,

Thanks.

Safari - iOS is is one of the few that get's it right.

Most android browsers will work properly if only numbers and the decimal 
point is typed. If the client enters a alpha character it can mess up AN 
because most android browsers do not support the 'keypress' event and or 
do return the correct character code.

I worked on a helper plugin that will fix android "chrome" & "FF" but 
not all. The proper order of event as you know is "keydown", "keypress", 
"input" & "keyup"

The following occurs with others;

iOS            Safari            number    "keydown", "keypress", 
"input" & "keyup" with correct key codes
                                         alpha        "keydown", 
"keypress", "input" & "keyup" with correct key codes

android    Chrome        number    "keydown", "keypress", "input" & 
"keyup" with correct key codes
                                         alpha        "keydown", "input" 
& "keyup"  with incorrect key codes

android    FF                  number    "keydown", "keypress", "input" 
& "keyup" with correct key codes
                                         ** alpha        "keydown", 
"keypress", "input" & "keyup" with correct key codes
                                         ** FF only works if there is an 
existing value otherwise 2 "input" events are thrown for every key

android    Dolphin        number    "keydown", "keypress", "input" & 
"keyup" with correct key codes - good android browser
                                         alpha        "keydown", 
"keypress", "input" & "keyup" with correct key codes

Amazon    Silk                                   ** primarily testing is 
not promising because the "input" event is thrown before "keydown
                                                            ** more 
testing needed but will wait until I get my hands on Fire HD

Windows Mobile          number    "keydown", "keyup" & "input" with 
correct key codes
                                         alpha         "keydown", 
"keyup" & "input" with correct key codes

I created this page to test http://www.decorplanit.com/autoKeyTest/

I also created a helper plugin that fixes Chrome and FF however it does 
not work on Windows mobile and Silk because the "input" event is out of 
sequence.

Let me know if you have any questions.

Bob
