### ISSUE TITLE
getArray mismatches with $.serializeArray

### ISSUE THREAD

**Issue by McFo** [BobKnothe/autoNumeric#126]
$.serializeArray() serializes `<input>`s, `<textarea>`s and `<select>`s, autoNumeric only searches for `<input>`s, so in the resulting object the values get out of sync.
Proposal (line ~1250):
```javascript
    var $field = $('form:eq(' + formIndex + ') input:eq(' + i + ')'),
```
gets
```javascript
    var $field = $('form:eq(' + formIndex + ') :input:eq(' + i + ')'),
```

EDIT: getString may have the same problem.

**Comment by BobKnothe** [comment]
John,
 
Thanks for the contribution.
 
I will test and get back to you within the next couple days.
 
Bob
 
--------- Original Message --------- Subject: [autoNumeric] getArray mismatches with $.serializeArray (#126)

**Comment by McFo** [comment]
Bob,

working with dynamically disabled form elements wreaks havoc as well. I propose following change:
```javascript
    var $field = $('form:eq(' + formIndex + ') :input:enabled:eq(' + i + ')'),
```

John

**Comment by BobKnothe** [comment]
John,

That makes sense. jQuery serialization only picks up successful controls and aN looks at all inputs. 

How much testing have you done?

Bob


 
Robert (Bob) Knothe

**Comment by McFo** [comment]
Bob,

only manual testing, using a table row containing a mix of ``input``s and ``select``s. I use a table for a list of similar entries with numerous fields. No ``textarea``s, though.
Additionally, Changing one certain ``select`` dynamically disables and enables certain other ``input``s and ``select``s in that row.

With the proposed change above everything works fine so far, even with multiple rows in edit mode.

John

**Comment by BobKnothe** [comment]
Is this something that could be put on jsfiddle?


 
Robert (Bob) Knothe

**Comment by McFo** [comment]
Unfortunately, no - corporate stuff.
On top of that, it's very lengthy with all that custom functions added.

**Comment by McFo** [comment]
Maybe I can upload a stripped down version tomorrow, when ... if I get permission from my boss.

**Comment by McFo** [comment]
Bob,

ok, I have done a lot of debugging and found the following:
In this line (1257):
```javascript
    var $field = $('form:eq(' + formIndex + ') input:eq(' + i + ')'),
```
you suppose, the whole form is used, but only inputs are parsed by `$.serializeArray()`.

I tried to utilize `.autoNumeric('getArray')` only on a selection of DOM objects, containing inputs, selects, buttons and other stuff.
`$.serializeArray()` serializes inputs, textareas and selects, but no buttons. `:input` on the other hand selects buttons as well.

My complete proposal consists of the following:
```javascript
    [...]
    getArray: function () {
        var isAutoNumeric = false,
            $this = autoGet($(this)),
            formFields = $this.serializeArray(),
//          formIndex = $('form').index($this),
            inputIndex = [];
        /*jslint unparam: true*/
        $.each(formFields, function (i, field) {
//            var $field = $('form:eq(' + formIndex + ') input:eq(' + i + ')'),
            var $field = $this.filter(':input:not(button):enabled:eq(' + i + ')'),
                settings = $field.data('autoNumeric');
            if ($field.length > 1) {
// Is this ok? inputIndex doesn't seem to get populated anywhere...
                $field = $field.eq(inputIndex[i]);
            }
    [...]
```

Fiddle: http://jsfiddle.net/McFo/nsduh031/12/ (using the browser console)

I should mention that `$('form').autoNumeric('getArray')` does NOT work in this case.

**Comment by BobKnothe** [comment]
John,
 
Thanks for your work on this hopfully I can review in the next couple days
 
I have made multiple changes over the last couple months so there could be remnants of code that I missed. 
 
Initially I used the name selector and everything was OK. Then a user pointed out what if inputs had shared names.  So I tried the below but the ++ iteration cause a problem so that is why I tried using the index selector. If the iteration could be fixed maybe I should go back to the name selector. Maybe something simple I missed - another pair of eyes (yours) might help.
 
I am out of my office but hopefully I can look at tonight tomorrow.
 
Thanks,
 
Bob
 
/** method to get the unformatted value from multiple fields */
 getArray: function () {
    var isAutoNumeric = false,
    $this = autoGet($(this)),
    formFields = $this.serializeArray(),
    formIndex = $('form').index($this),
   inputIndex = [];
 /*jslint unparam: true*/
 $.each(formFields, function (i, field) {
    var $field = $('form:eq(' + formIndex + ') input[name="' + decodeURIComponent(field.name) + '"]'),
   settings = $field.data('autoNumeric');
   if ($field.length > 1) {
       if (inputIndex[decodeURIComponent(field.name)] === undefined) {
            inputIndex[decodeURIComponent(field.name)] = 0;
       } else {
           inputIndex[decodeURIComponent(field.name)]++;
 }
 $field = $field.eq(inputIndex[decodeURIComponent(field.name)]);
 }
 if (typeof settings === 'object') {
   if (field.value !== '') {
        field.value = $field.autoNumeric('get').toString();
   }
   isAutoNumeric = true;
   }
 });
 
 
--------- Original Message --------- Subject: Re: [autoNumeric] getArray mismatches with $.serializeArray (#126)

**Comment by BobKnothe** [comment]
John,

I had time to look at your proposal and while it works in some cases it does not work in all - this is because of my code did not take into account all the variation. So I have rewritten the "getArray" method. Before posting I was hoping you could test and let me know if it works in your application.

Thanks Bob


getArray: function (outPut) {
var isAutoNumeric = false,
$this = autoGet($(this)),
formFields = $this.serializeArray(),
formIndex = $('form').index($this),
allFormElements = $('form:eq(' + formIndex + ')'),
aiIndex = [], /** all input index */
scIndex = [], /** successful control index */
rsubmitterTypes = /^(?:submit|button|image|reset|file)$/i, /** from jQuery serialize method */ 
rsubmittable = /^(?:input|select|textarea|keygen)/i,
rcheckableType = /^(?:checkbox|radio)$/i,
count = 0;
/*jslint unparam: true*/	
/** index of successful elements */
$.each(allFormElements[0], function (i, field) {
if (field.name !== '' && rsubmittable.test(field.localName) && !rsubmitterTypes.test(field.type) && !field.disabled && (field.checked || !rcheckableType.test(field.type))) {
scIndex.push(count);
count = count + 1;
} else {
scIndex.push(-1);
}						 
});
/** index of all inputs tags except checkbox */		
count = 0;
$.each(allFormElements[0], function (i, field) {
if (field.localName === 'input' && field.type !== 'checkbox') {
aiIndex.push(count);
count = count + 1;
} else {
aiIndex.push(-1);
if (field.type === 'checkbox') {
count = count + 1;
}
}							 
});
$.each(formFields, function (i, field) {
var scElement = $.inArray(i, scIndex);
if (scElement > -1 && aiIndex[scElement] > -1) {
var testInput = $('form:eq(' + formIndex + ') input:eq(' + aiIndex[scElement] + ')'),
settings = testInput.data('autoNumeric');
if (typeof settings === 'object') {
field.value = $('form:eq(' + formIndex + ') input:eq(' + aiIndex[scElement] + ')').autoNumeric('get', outPut).toString();
isAutoNumeric = true;
}
}
});
/*jslint unparam: false*/
if (!isAutoNumeric) {
$.error("None of the successful form inputs are initialized by autoNumeric.");
}
return formFields;
},

**Comment by McFo** [comment]
Bob,

I currently have urgent assignments at work to do, but will come back to your rewritten code tomorrow or Wednesday.

John

**Comment by BobKnothe** [comment]
John,

Thanks  - I did make a small change - see below.

Bob

getArray: function (outPut) {
var isAutoNumeric = false,
$this = autoGet($(this)),
formFields = $this.serializeArray(),
formIndex = $('form').index($this),
allFormElements = $('form:eq(' + formIndex + ')'),
aiIndex = [], /** all input index */
scIndex = [], /** successful control index */
rsubmitterTypes = /^(?:submit|button|image|reset|file)$/i, /** from jQuery serialize method */
rsubmittable = /^(?:input|select|textarea|keygen)/i, /** from jQuery serialize method */
rcheckableType = /^(?:checkbox|radio)$/i,
rnonAutoNumericTypes = /^(?:button|checkbox|color|date|datetime|datetime-local|email|file|image|month|number|password|radio|range|reset|search|submit|time|url|week)/i,
count = 0;
/*jslint unparam: true*/
/** index of successful elements */
$.each(allFormElements[0], function (i, field) {
if (field.name !== '' && rsubmittable.test(field.localName) && !rsubmitterTypes.test(field.type) && !field.disabled && (field.checked || !rcheckableType.test(field.type))) {
scIndex.push(count);
count = count + 1;
} else {
scIndex.push(-1);
}
});
/** index of all inputs tags */
count = 0;
$.each(allFormElements[0], function (i, field) {
if (field.localName === 'input' && (field.type === '' || field.type === 'text' || field.type === 'hidden' || field.type === 'tel')) {
aiIndex.push(count);
count = count + 1;
} else {
aiIndex.push(-1);
if (field.localName === 'input' && rnonAutoNumericTypes.test(field.type)) {
count = count + 1;
}
}
});
$.each(formFields, function (i, field) {
var scElement = $.inArray(i, scIndex);
if (scElement > -1 && aiIndex[scElement] > -1) {
var testInput = $('form:eq(' + formIndex + ') input:eq(' + aiIndex[scElement] + ')'),
settings = testInput.data('autoNumeric');
if (typeof settings === 'object') {
field.value = $('form:eq(' + formIndex + ') input:eq(' + aiIndex[scElement] + ')').autoNumeric('get', outPut).toString();
isAutoNumeric = true;
}
}
});
/*jslint unparam: false*/
if (!isAutoNumeric) {
$.error("None of the successful form inputs are initialized by autoNumeric.");
}
return formFields;
},

**Comment by McFo** [comment]
Bob,

I've been able to test your proposed changes within our application, they seem to work fine. However, your /* */ comments seem to be messed up, I hope, I have included all necessary changes.

btw: you can enclose code with triple backticks and the language name, this gets you syntax highlighting as well:
\`\`\`javascript
  // code...
\`\`\`


```javascript
getArray: function (outPut) {
    var isAutoNumeric = false,
        $this = autoGet($(this)),
        formFields = $this.serializeArray(),
        formIndex = $('form').index($this),
        allFormElements = $('form:eq(' + formIndex + ')'),
        aiIndex = [], /* all input index */
        scIndex = [], /* successful control index */
        rsubmitterTypes = /^(?:submit|button|image|reset|file)$/i, /* from jQuery serialize method */
        rsubmittable = /^(?:input|select|textarea|keygen)/i, /* from jQuery serialize method */
        rcheckableType = /^(?:checkbox|radio)$/i,
        rnonAutoNumericTypes = /^(?:button|checkbox|color|date|datetime|datetime-local|email|file|image|month|number|password|radio|range|reset|search|submit|time|url|week)/i,
        count = 0;
    /*jslint unparam: true*/
    /* index of successful elements */
    $.each(allFormElements[0], function (i, field) {
        if (field.name !== '' && rsubmittable.test(field.localName) && !rsubmitterTypes.test(field.type) && !field.disabled && (field.checked || !rcheckableType.test(field.type))) {
            scIndex.push(count);
            count = count + 1;
        } else {
            scIndex.push( - 1);
        }
    });
    /* index of all inputs tags */
    count = 0;
    $.each(allFormElements[0], function (i, field) {
        if (field.localName === 'input' && (field.type === '' || field.type === 'text' || field.type === 'hidden' || field.type === 'tel')) {
            aiIndex.push(count);
            count = count + 1;
        } else {
            aiIndex.push( - 1);
            if (field.localName === 'input' && rnonAutoNumericTypes.test(field.type)) {
                count = count + 1;
            }
        }
    });
    $.each(formFields, function (i, field) {
        var scElement = $.inArray(i, scIndex);
        if (scElement > - 1 && aiIndex[scElement] > - 1) {
            var testInput = $('form:eq(' + formIndex + ') input:eq(' + aiIndex[scElement] + ')'),
                settings = testInput.data('autoNumeric');
            if (typeof settings === 'object') {
                field.value = $('form:eq(' + formIndex + ') input:eq(' + aiIndex[scElement] + ')').autoNumeric('get', outPut).toString();
                isAutoNumeric = true;
            }
        }
    });
    /*jslint unparam: false*/
    if (!isAutoNumeric) {
        $.error("None of the successful form inputs are initialized by autoNumeric.");
    }
    return formFields;
},

```

John

**Comment by McFo** [comment]
Woops.

**Comment by BobKnothe** [comment]
John,

Glad it is working - will post when I get back from Deutschland. 

Thanks for the hint on syntax highlighting. 

Bob


 
Robert (Bob) Knothe

**Comment by McFo** [comment]
Well, greetings from Hamburg, then ;-D

**Comment by BobKnothe** [comment]
I was in Koln for a fair


 
Robert (Bob) Knothe
