### ISSUE TITLE
Wrong rounding in IE

### ISSUE THREAD

**Issue by zgredo** [BobKnothe/autoNumeric#145]
There is a problem with rounding numbers with 15 decimal places in IE, but not when you enter the number manualy with keyboard, only at initializing and paste. For example 0.000000000000009 is past as 0.000000000000008.

**Comment by BobKnothe** [comment]
Please let me know which version of autoNumeric you are using and the paste method.

Thkx

**Comment by BobKnothe** [comment]
Z.

After investigating your issue this appears to be a browser browser bug 
that is unique to IE.

autoNumeric checks for very small numbers via the checkSmall function. 
The number you are pasting is converted to 9e-15 which then has 10 added 
to it which converts it back to 10.000000000000009 and then converted to 
a string. The problem IE javascript engine when adding 10 to 9e-15 
converts it to 10.000000000000008.

Unfortunately I cannot think of any work around to fix IE's bug. I will 
mention this in the known issues section on the next update.

Thanks for the info.

Bob

**Comment by peterboccia** [comment]
The problem here is not IE, but you have to know that all the browser use a different way to rounding and managing big number. In this case I discovered this behavior bitterly on my skin, when in a project with very big number (money) we have a big loss of information with other plugin that doesn't handle this js limitation.
Take a look at the plugin of @MikeMcl: [Big Number](https://github.com/MikeMcl/bignumber.js/)
Take a minute to check around this behavior.

**Comment by BobKnothe** [comment]
I have incorporated Big Number into version 2

https://github.com/BobKnothe/autoNumeric/tree/master/autoNumeric-2.0
