### ISSUE TITLE
Autonumeric not working properly when vMax length is more than 20

### ISSUE THREAD

**Issue by manandkumaar** [BobKnothe/autoNumeric#151]
Three zeroes are getting deleted while deleting the 0 after 2 in this 200,000,000,000 When vMax length more than 20.

When delete the 0 after 2, i get 200,000,000 instead of 20,000,000,000.

Sample code :-
$('input').autoNumeric({aPad: 'true', aSep: ',', aSign: '', aDec: '.', vMax: '99999999999999999999999', vMin: '0'});

**Comment by BobKnothe** [comment]
Manand,

Thank you for your interest in autoNumeric and notifying me of the issue. 

I will check into this and let you know my finding. I suspect this has to do with java scripts numeric limitation. 

Bob

 
Robert (Bob) Knothe

**Comment by BobKnothe** [comment]
This appears to be a autoNumeric bug in the autoStrip function.
 
It appears that if there is a zero to the right of the caret this happens.
 
Will dig deeper and hopefully post a fix within the next couple days
 
 
 
--------- Original Message --------- Subject: [autoNumeric] Autonumeric not working properly when vMax length is more than 20 (#151)

**Comment by BobKnothe** [comment]
If you comment line 195 and test - that would be appreciated.
 
if (parts[0].length > settings.mInt && parts[0].charAt(0) === '0') { /** strip leading zero if need */
      // parts[0] = parts[0].slice(1); // line 195
 }
 
 
--------- Original Message --------- Subject: [autoNumeric] Autonumeric not working properly when vMax length is more than 20 (#151)

**Comment by BobKnothe** [comment]
Manand,
 
Hope I have you name properly.
 
After digging into this my initial thoughts that the issue was related to javascript's numeric inaccuracies is correct.
 
When converting your vMax: '99999999999999999999999' to a number javascript converts it to a exponent notation  ["1e+23"] and this is causing the issue.
 
Please disregard my earlier suggestion and try one of the following are possible solutions.
 
 
+ Reduce your vMax to 15 significant digits. FYI - if you add decimal place the number of significant digits need to be reduced. 
+ On line 136 if you change this as follows  
+ From - settings.mInt = Math.max(vmax[0].length, vmin[0].length, 1); 
+ To - settings.mInt = 22; //"please note this will solve your deletion of characters but accuracy may still be an issue. 

  

 I am working on a new version that incorporate Big.js that will address javscript's numeric limitations. Hope to have it launch withing the next month, 
 Hopefully my above suggestions are a temporary and you can wait for my upgrade.
 Best regards,
  
 Bob
  
  
 
--------- Original Message --------- Subject: [autoNumeric] Autonumeric not working properly when vMax length is more than 20 (#151)

**Comment by manandkumaar** [comment]
Thank you Bob :) 
Temp fix is working fine. I am waiting for the permanent fix.

Regards,
Anand
