### ISSUE TITLE
Calculation result decimals stay 0

### ISSUE THREAD

**Issue by matthijs110** [BobKnothe/autoNumeric#160]
Hello,

I am trying to calculate 2 floats in JQuery. One has 0 decimals, the other has 3 decimals. The numbers before the comma are calculated right. But the decimals itself are not (behind the ','). How can I fix this?

**Example:**
```javascript
var inputAmount = '3'; // Value from input
var inputPrice = '2,567'; // Value from input

if(inputAmount == ""){
   inputAmount = 0;
}
if(inputPrice == ""){
   inputAmount = 0.000;
}

var calculatedPrice = (parseFloat(inputAmount) * parseFloat(inputPrice));

setTimeout(function() {
     $('input[name="inputResult"]').autoNumeric('set', calculatedPrice.toFixed(3));  // Set result to input
}, 500);
```
*3 times 2,567 = 7,701*

The result however becomes: *6000*

Where is the mistake? I can't find it. I tried many different options. Does someone know where it goes wrong?

**Comment by BobKnothe** [comment]
Matthijs,

If the ',' comma is a thousand separator then I believe your issue is 
this line:

var  inputPrice=  '2,567';// Value from input

parseFloat(2,567) // becomes 2

If you are getting a a value from a autoNumeric controlled input use 
autoNumeric 'get' method $(selector).autoNumeric('get'); //2567

Hope this helps - if so please close the issue.

Bob

**Comment by matthijs110** [comment]
That did the job :)

Thanks @BobKnothe !

**Comment by BobKnothe** [comment]
Glad it helped
