### ISSUE TITLE
Add a format() callback

### ISSUE THREAD

**Issue by kito99** [BobKnothe/autoNumeric#187]
We have a requirement to display ".00" instead of "0.00". I was able to do this by patching the original source, but that's a pain to maintain. Having a simple callback that's always executed when the value is updated (for display, not the numeric value) would be very helpful. Right now I'm doing this in the focusout.autoNumeric event handler and in checkEmpty() function.

**Comment by BobKnothe** [comment]
Kito,It's been a long time - hope all is well. I am not sure what you are asking!  When you say '000' do you mean '0.00'?Can you rephase you request or post an example?Bob  -------- Original Message -------- Subject: [autoNumeric] Add a format() callback (#187) From: "Kito D. Mann" <notifications@github.com> Date: Tue, December 29, 2015 2:55 pm To: BobKnothe/autoNumeric <autoNumeric@noreply.github.com>  We have a requirement to display "00" instead of "000" I was able to do this by patching the original source, but that's a pain to maintain Having a simple callback that's always executed when the value is updated (for display, not the numeric value) would be very helpful Right now I'm doing this in the focusoutautoNumeric event handler and in checkEmpty() function —Reply to this email directly or view it on GitHub.

**Comment by kito99** [comment]
Hey Bob! Nice to hear from you as well.

I meant ".00" instead of "0.00". Basically remove the leading zero if the value is zero, but still display the zeros after the decimal.

**Comment by Raylehnhoff** [comment]
@kito99, I know this is a pretty old issue, but I committed PR #204 which will emit the event `autoNumeric:itemFormatted` on focusout. This event will trigger after all formatting is done, but will NOT trigger when the values are updating as the user is typing (see the "2 India's lakhs ( on values below 1 billion)" example in index.html for this. 

I don't think it would be wise to emit an event while the user is actively updating the textbox.

**Comment by BobKnothe** [comment]
@Raylehnhoff, Just finding time to catch up on some old issues.

Are you suggesting to create a special event that @kito99 can use to update the display?

Why create a special event versus listening for the change event a couple line above?

**Comment by Raylehnhoff** [comment]
I think the intention was to have an event that let you know for sure that
formatting was done, versus change which other things can listen to and
manipulate.

It's fairly standard to have library specific callbacks for things like
this - I'm happy to defer to your judgement though.

**Comment by BobKnothe** [comment]
Ray,

Thank you - I respect your input. 

I can see your point - now the question is doe the custom event get thrown on the focusout or focusout with a change?

Bob

 
Robert (Bob) Knothe

**Comment by Raylehnhoff** [comment]
I'd have to defer to your knowledge there. I think it should yet thrown
when the control is done formatting, essentially at the end of the
execution chain.

**Comment by BobKnothe** [comment]
It actually formats  on "focusout" regardless if the value has changed or not. So if the user enters and exits without pressing a key it still formats. The last conditional statement checks ans see if the value have changed and if "true" throws the change event.
 
 I will contemplate over a beer:-)
 
 
 
--------- Original Message --------- Subject: Re: [BobKnothe/autoNumeric] Add a format() callback (#187)

**Comment by BobKnothe** [comment]
Kito,

Hope you had a good weekend.

Have you had time to look at the proposal for the format callback? Would that work in your case?

If so while I am making this mod is there any other call back that might be a good idea?

Bob 

FYI - I sent a private email three weeks ago but the address may be bad - anyway please take a look at Ray's proposal.

**Comment by kito99** [comment]
Sorry for the delay. Way behind on e-mail :-).

Would Ray's change allow us to do additional modifications to the format,
or would it be too late?

**Comment by Raylehnhoff** [comment]
It would be too late, since it fires after all formatting has triggered.

**Comment by BobKnothe** [comment]
Kito,

Here are a few questions on the behavior before I dig into this possible 
mod:

  * You do not want the zero to be automatically entered while typing?
  * On focusout if there is not leading zero ".99" you do is added
  * If a client enters the Zero manually "0.99" do you want it left or
    removed?
  * Using the "set" to format a default value "0.99" do you want the
    zero left or striped?


Bob

**Comment by AlexandreBonneau** [comment]
Without answers for a few month, I took on to 'fix' that issue by creating a new `'autoNumeric:formatted'` event that is sent as soon as the input value is formatted.

This event is sent after each key press, if the resulting value has changed, which means if the user hit a key that does not result in the input value changing, no such event is sent.

Please note that If you need to call a callback on blur, you can listen to the 'change' event that is now correctly sent (cf. issue #292).

**Comment by kito99** [comment]
@AlexandreBonneau, it looks like you still can't customize the formatting by using this event, which is what the original request was. Am I wrong?

**Comment by AlexandreBonneau** [comment]
@kito99 I'm not sure to follow.

You can know listen to the `'autoNumeric:formatted'` event, then call any custom function you need to change the input value on the fly.

In the initial comment, you talked about displaying `".00"` instead of `"0.00"`, you could check the input value after every `autoNumeric:formatted` event and change it to `"0.00"` as needed.

So currently, all the autoNumeric formatting is done, then you can modify the value from there.
Wouldn't that solve your initial problem?

**Comment by kito99** [comment]
@AlexandreBonneau yes, that would do it. I misread the earlier explanation. Thanks!

**Comment by AlexandreBonneau** [comment]
@kito99 You're welcome!
