### ISSUE TITLE
Unbind issue

### ISSUE THREAD

**Issue by saruman** [BobKnothe/autoNumeric#201]
Hello.
I have trouble with your plugin when unbind and object previously bind with autoNumeric.

The first time works good, but after using ".unbind()", autoNumeric stop working.  I tried to re bind it but it doesn't work.

$(element).unbind();  // I need to undbind all the events from the object on the fly.
// some code here
$(element).autoNumeric('init');  // after undbind my object, autonumeric init doen't work.

Please let me know what I'm doing wrong.  I have the latest version (1.9.43)

**Comment by BobKnothe** [comment]
Can you post a jsFiddle?

**Comment by Raylehnhoff** [comment]
Hi @BobKnothe ,

I reproduced this in this jsbin:

http://jsbin.com/fayadocaro/1/edit?html,js,console,output

@saruman The issue is, `unbind()` removes event handlers, and in order to call init again on an object, the $.autoNumeric of the JQuery element needs to be set to null. I successfully got this working under a simple test case by removing the autoNumeric function off of the element via:

see:

http://jsbin.com/mitemovebo/edit?html,js,output

The test case was this:

````JS
$(document).ready(function(){
	$('.dollar_value').autoNumeric('init', { aSign: '$' });
  
  setTimeout(function(){
    $('.dollar_value').each(function(){
      $(this).autoNumeric = null;
      $(this).autoNumeric('init', { aSign: '$' });
      });
  },1500);
  
});
````

**Comment by BobKnothe** [comment]
I hope that Ray's answer / solution addresses your situation.
