### ISSUE TITLE
pasting fails with aDec different from period.

### ISSUE THREAD

**Issue by rhyek** [BobKnothe/autoNumeric#261]
Fixed with #260.

**Comment by BobKnothe** [comment]
Thank you for all of your attention.

I just up loaded a new file that includes your work on the "paste" event but many new features.

Check it out - look forword to hear your comments.

**Comment by rhyek** [comment]
Looks great! Is it considered stable? When can we expect to install from `npm` and have version 2 be the default module? Also, docs? :)

**Comment by BobKnothe** [comment]
There have been a lot of people using this without issue so yes it is stable.

I am pretty busy - hopefully l can complete the docs within the next 2 weeks.

There is a "bug issue #250" in version 1.9.46 on android chrome browser that I would like to fix first. They call it a bug but I just say Chrome sucks - no support for keypress and keycodes. So i am trying to find this first then incorporate that into V2.

**Comment by BobKnothe** [comment]
here is an example of the "aScale" option try focus in and out

http://codepen.io/RJ_Knothe/pen/ZBWMrX

**Comment by rhyek** [comment]
@BobKnothe, I just tried one of my codepens on my android phone and indeed, it's not working. This is rather important to me and I'd like to help. What exactly do you think is happening and, in the 2.0 file, where do you think I should start looking to test/change code?

**Comment by BobKnothe** [comment]
@rhyek,

This issue is that the current version of Chrome for Android does the throw the "keypress" event and that is where aN (autoNumeric) does the min/max check.

Back in 2014 this issue was a big deal and then android added the "keypress" support only to drop is later unknown to me.

Before they added (at least temporarily) "keypress" I had started working on a helper plugin but later abandoned this once android chrome added the "keypress" support. In hindsight creating a helper plugin may only create a dependency that is too complicated.

IMHO one of two way this can be taken:

- Test the input at "keydown" and in "keyup" test if there is no "keypress" and then assume this is a android browser and do the min/max test and over write the value.

- An alternative is to create a  max length to the input - but doing this may limit the precision min/max that aN2 is all about.

If you have any suggestions I am open.

**Comment by BobKnothe** [comment]
Let me correct myself!

Android does NOT throw the "keypress" event which is critical to how aN operates. I believe this needs to be checked on "keyup" or "input" and compensated for the lack of "keypress?

**Comment by rhyek** [comment]
@BobKnothe, I was actually going to reply saying I tested it briefly and it seems when typing, formatting works, but on my input event handler, `.autoNumeric('get')` never changes. Didn't test any other functionality and options were just the default.

This seems like a real problem. You're right in that this needs to be fixed before 2.0 is released.

With regards to the event that should be used, I haven't really looked at your current code in depth, but I would guess the best event would be `keydown`. `input` would be too late.

Is there a specific reason you need `keypress` currently? Would it be possible to handle everything on either `keydown` or `keyup` (just one, not both)?

**Comment by BobKnothe** [comment]
Can you open a new issue rather then comment on a old issue?

As far as the keypress event that is where e.prevent is used. Yes keydown seems to be the logical point to start.

**Comment by rhyek** [comment]
I want to get a better idea of what's going on before opening a new issue. I tried it on an Android VM and everything works fine. I opened up a community for you on gitter. You should have gotten an invitation.

**Comment by BobKnothe** [comment]
No invatation yet

I just posted a mod to the "get" method that will get the value from the input and not the rawValue for all inputs with the exception of "eDec* & "aScale"

in android chrome all character codes = 229
there is not keypress event and that is where the min/max test is done and the updating of the rawValue.

**Comment by rhyek** [comment]
https://gitter.im/autoNumeric
