### ISSUE TITLE
`leadingZero` option `deny` does not function correctly and deletes some of the zero to the right of the caret

### ISSUE THREAD

**Issue by BobKnothe** [BobKnothe/autoNumeric#302]

**Comment by AlexandreBonneau** [comment]
Possibly related ; when I use those options `{ digitGroupSeparator: '.', decimalCharacter: ',', decimalCharacterAlternative: '.', currencySymbol: '\u00a0€', currencySymbolPlacement: 's', roundingMethod: 'U', minimumValue: '0', leadingZero: 'deny' }`, if you have `|8.000,00 €` in the input, then type `10`, you get `10|8.000,00 €` which is ok, but if then you hit `delete`, you get `10|0,00 €` instead of `10|.000,00 €`

**Comment by AlexandreBonneau** [comment]
Another possibly related problem, while still using the same options as above, if you have `1|00,00 €` in the input, then type `0`, you get `10|0,00 €` instead of `1.0|00,00 €`

**Comment by BobKnothe** [comment]
Look at the following codepen with the proposed fix

 http://codepen.io/RJ_Knothe/full/NbErYJ/

**Comment by AlexandreBonneau** [comment]
This looks good and fix both the use case I mentioned.

Here is the [updated codepen](http://codepen.io/AnotherLinuxUser/pen/qqLBEO?editors=1011) with the last input allowing you to test with the specific options I used.

**Comment by AlexandreBonneau** [comment]
Fixed in `next`.
