### ISSUE TITLE
Some issues with your updates?!

### ISSUE THREAD

**Issue by eisbehr-** [BobKnothe/autoNumeric#377]
Hello again,

I was about to test the fix of a bug and saw, that the version here on git should be 2.0.1 (as mentioned in the readme). On NPM the readme still shows 2.0.0, but NPM itself has version 2.0.1. But the real problem seems to be, that the `dist` folder was not updated after your changes. So it looks like you've incremented the version, but did no rebuild.

There is even no release for 2.0.1.

**Comment by AlexandreBonneau** [comment]
Hey @eisbehr-, thanks for the heads up.

`2.0.0` did not ship the `dist` folder (cf. issue https://github.com/BobKnothe/autoNumeric/issues/373), `2.0.1` fixed it by including it for the publishing to npmjs, which means if you can see a `dist` folder, it means it has been updated to `2.0.1`.

The fact that npmjs shows the readme which mention `2.0.0` is because I published `2.0.1` while having forgot to update the readme, my bad ;P

I think to prevent this kind of incoherent information, I'll just scrap any version number reference from the readme, and let the npm badge show the latest `master` version.

You are however refering to changes that would not have been present in the dist files, could you please be more specific? It's possible we missed something there.

**Comment by eisbehr-** [comment]
I was about to check the changes from #371 and noticed this. When I compare the files in release 2.0.0 and the current `dist` folder, the file contents are exactly the same. So I think there are changes missing. Even if I look in the histroy of the file, there was no changes 6 days ago, but you fixed the bug just 3 days ago.

And there seems still to be another problem. The library is even not updated on cdnjs and jsdeliver. 
http://www.jsdelivr.com/projects/autonumeric (lastest: 2.0.0)
https://cdnjs.com/libraries/autonumeric (lastest: 1.9.46)

**Comment by AlexandreBonneau** [comment]
The jsdelivr bot update the library automatically since I first committed to their repository.
I noticed it usually takes a few hours (even perhaps a day) to crawl this repo and update their cdn. It should go up *soon*.

About cdnjs, you are the first one to made us aware about it not being updated.
We'll add this cdn to our list too, thanks :)

I'm about to push a fix for #367, so everything should be ok then.

**Comment by AlexandreBonneau** [comment]
Since issue #367 is solved, and apparently so is issue #371, it means this one is solved too!

If that's not the case, feel free to reopen it.

**Comment by eisbehr-** [comment]
I'm pretty sure that jsDelivr has a problem, because it didn't noticed any changes the last days. 😉  I use jsDelivr by myself on other projects and normally it takes 0,5-3h to update.

**Comment by AlexandreBonneau** [comment]
There, it's [up-to-date](http://www.jsdelivr.com/projects/autonumeric) with v2.0.7.

Note to self; the jsdelivr bot only parse the github **releases**, not the npm published version.

**Comment by eisbehr-** [comment]
> Note to self; the jsdelivr bot only parse the github releases, not the npm published version.

You can draft a `release` or just `tag` the version, both will be noticed afaik. Glad it worked now!

**Comment by AlexandreBonneau** [comment]
Good to know, thanks
