### ISSUE TITLE
autoNumeric 2.0.7 npm packages causes build error with typescriptify + browserify

### ISSUE THREAD

**Issue by jsmarsch** [BobKnothe/autoNumeric#389]
When building a typescript project with gulp, browserify, and typescriptify, we get build errors from the autonumeric npm package:

`TypeScript error: main.ts(24,8): Error TS2656: Exported external package typings file 'node_modules/autonumeric/typings.d.ts' is not a module. Please contact the package author to update the package definition.`

If we edit the node_moduels/autonumeric/package.json file and remove the typings setting, we get past this error and then encounter issue #388

**Comment by AlexandreBonneau** [comment]
There is an interesting answer about how to [generate](http://stackoverflow.com/questions/12687779/how-do-you-produce-a-d-ts-typings-definition-file-from-an-existing-javascript#12695001) a `typings.d.ts` file, but since that file has never been updated to reflect the current real version of autoNumeric, we can assume it's not widely use and we'll just remove it.
