### ISSUE TITLE
Do not add decimal padding when a number without decimals has been inserted

### ISSUE THREAD

**Issue by mvanroon** [BobKnothe/autoNumeric#409]
When option `allowDecimalPadding` is set to `true`
500 will become 500.00 and 500.40 will remain 500.40

when set to `false` 500 will remain 500 but 500.40 becomes 500.4

500.4 looks weird for currencies so ideally there should be a way to only add decimal padding when the input already has decimals so that:

500 will remain 500, but 500.4 will become 500.40 and 500.30 will stay 500.30

`allowDecimalPaddingForWholeNumbers` or something similar?

**Comment by AlexandreBonneau** [comment]
Or we could modify `allowDecimalPadding` so that it allows 3 variations:
- `AutoNumeric.options.allowDecimalPadding.always` : always pad with zeros (previously `padding`)
- `AutoNumeric.options.allowDecimalPadding.never` : never pad with zeros (previously `noPadding`)
- `AutoNumeric.options.allowDecimalPadding.floats` : pad with zeros only when there are decimals

If you have a better name for the new last option, let me know ;)

**Comment by mvanroon** [comment]
Agreed. Be aware that allowDecimalPadding currently accepts true or false
